### Récupérer les entreprises
GET http://localhost:3000/api/admin/company
Content-Type: application/json

### creation d'une entreprise
POST http://localhost:3000/api/company
Content-Type: application/json

{
    "name": "Entreprise créée",
    "siret": "51234567891234",
    "localisation": "Pau"
}

### creation d'un user
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "lastname": "Emma",
    "firstname": "Postgres",
    "phonenumber": "01010101010",
    "email": "emma.postgres@exemple.com",
    "password": "gargouille2025"
}

### authentification
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "emma.postgres@exemple.com",
    "password": "gargouille2025"
}

### trier les user
GET http://localhost:3000/api/admin/user/filter?lastnameSelected
Content-Type: application/json

### lister les user
GET http://localhost:3000/api/admin/user
Content-Type: application/json